openapi: 3.0.0
servers:
  - url: https://143.198.74.202
    description: Button Device Server
  ##- url: http://localhost
  ##  description: Button Device Server
info:
  title: Button Request
  version: 1.0.0
  description: >
    # Introduction
    
    Button Request is a platform for someone who want to replace tedious and repeated message with 
    a button. 
    
    ## API Categories

    There are only 1 category of API
   
    Below is the API classification
    
      - Button Device API

    ## API Operations

    ### Button Device API
    
    Using the Button Device API, you may send the defined messages to the console.

   

    # Authentication
  
    ##For Button Device API, the device id and the bearer token is the authentication method 



tags:
  - name: deviceAPI
    description: Button Device API
  - name: MessageAPI
    description: Fetch/Pin/Unpin/Delete Message through Normal API
  - name: DeviceList
    description: Manage Device
  - name: DeviceShare
    description: Device Share
  - name: MobileAccessToken
    description: Mobile Access Token
paths:
  '/deviceAPI/v1/{deviceId}':
    post:
      security:
        - DeviceAPIAuth: []    
      tags:
        - deviceAPI
      description: Send a Button Request
      parameters:
          - name: deviceId
            in: path
            required: true
            deprecated: false
            schema:
              type: varchar
          - name: button_id
            in: query
            required: true
            deprecated: false
            schema:
              type: varchar
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
  '/api/v1/message/fetch':   
    post:
      security:
        - NormalAPIAuth: []    
      tags:
        - MessageAPI
      description: Fetch all messages
      
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'

  '/api/v1/message/pinStatus/{msgId}/{action}': 
    post:
      security:
        - NormalAPIAuth: []    
      tags:
        - MessageAPI
      description: Pin or Unpin Message
      parameters:

          - name: msgId
            in: path
            required: true
            deprecated: false
            schema:
              type: varchar
          - name: action
            in: path
            required: true
            deprecated: false
            schema:
              type: varchar
              enum:
                - pin
                - unpin

      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
  
  '/api/v1/message/delete/{msgId}':    
    post:
      security:
        - NormalAPIAuth: []    
      tags:
        - MessageAPI
      description: Delete Message
      parameters:

          - name: msgId
            in: path
            required: true
            deprecated: false
            schema:
              type: varchar
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'

  '/api/v1/buttonDevice/myDevice/list/{device_id}': 
    post:
      security:
        - NormalAPIAuth: []    
      tags:
        - DeviceList
      description: Fetch Device List
      parameters:

          - name: device_id
            in: path
            required: true
            deprecated: false
            schema:
              type: varchar

      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
  '/api/v1/buttonDevice/myDevice/repeatedMessage/{device_id}/{action}': 
    post:
      security:
        - NormalAPIAuth: []    
      tags:
        - DeviceList
      description: Repeated Message Settings
      parameters:
          - name: device_id
            in: path
            required: true
            deprecated: false
            schema:
              type: varchar
          - name: action
            in: path
            required: true
            deprecated: false
            schema:
              type: varchar
              enum:
                - allow
                - disallow
     

      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'

  '/api/v1/buttonDevice/myDevice/{device_id}/buttonId/{action}': 
    post:
      security:
        - NormalAPIAuth: []    
      tags:
        - DeviceList
      description: Button Message Update
      parameters:
          - name: device_id
            in: path
            required: true
            deprecated: false
            schema:
              type: varchar
          - name: action
            in: path
            required: true
            deprecated: false
            schema:
              type: varchar
              enum:
                - delete
                - updateOrNew
          - name: passData
            in: query
            required: true
            deprecated: false
            schema:
              type: varchar
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
  
  '/api/v1/buttonDevice/deviceSharedToMe/fetch': 
    post:
      security:
        - NormalAPIAuth: []    
      tags:
        - DeviceShare
      description: Fetch Device Shared To Me
      
          
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
  '/api/v1/buttonDevice/deviceSharedToMe/delete/{case_id}': 
    post:
      security:
        - NormalAPIAuth: []    
      tags:
        - DeviceShare
      description: Give up Sharee Right
      parameters:
          - name: case_id
            in: path
            required: true
            deprecated: false
            schema:
              type: varchar
         
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
  
  '/api/v1/buttonDevice/shareDevice/new/{email}/{device_id}': 
    post:
      security:
        - NormalAPIAuth: []    
      tags:
        - DeviceShare
      description: Share Device To
      parameters:
          - name: device_id
            in: path
            required: true
            deprecated: false
            schema:
              type: varchar
          - name: email
            in: path
            required: true
            deprecated: false
            schema:
              type: email
         
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
  '/api/v1/buttonDevice/shareDevice/changeRight/{case_id}/{right}': 
    post:
      security:
        - NormalAPIAuth: []    
      tags:
        - DeviceShare
      description: Change Sharee Right
      parameters:
          - name: case_id
            in: path
            required: true
            deprecated: false
            schema:
              type: varchar
          - name: right
            in: path
            required: true
            deprecated: false
            schema:
              type: varchar
              enum:
                - basic
                - middle
                - advanced
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'

  '/api/v1/buttonDevice/myDevice/new/{nickname}': 
    post:
      security:
        - NormalAPIAuth: []    
      tags:
        - DeviceList
      description: New Device
      parameters:
          - name: nickname
            in: path
            required: true
            deprecated: false
            schema:
              type: varchar
          
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'

  '/api/v1/mobileDevice/fetch': 
    post:
      security:
        - NormalAPIAuth: []    
      tags:
        - MobileAccessToken
      description: Fetch Mobile Access Token
          
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'

  '/api/v1/mobileDevice/new/{nickname}': 
    post:
      security:
        - NormalAPIAuth: []    
      tags:
        - MobileAccessToken
      description: New Mobile Access Token
      parameters:
          - name: nickname
            in: path
            required: true
            deprecated: false
            schema:
              type: varchar
          
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
  
  '/api/v1/mobileDevice/amend/{case_id}': 
    post:
      security:
        - NormalAPIAuth: []    
      tags:
        - MobileAccessToken
      description: Amend Nickname
      parameters:
          - name: case_id
            in: path
            required: true
            deprecated: false
            schema:
              type: varchar
          - name: nickname
            in: query
            required: true
            deprecated: false
            schema:
              type: varchar
          
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
  '/api/v1/mobileDevice/revoke/{case_id}': 
    post:
      security:
        - NormalAPIAuth: []    
      tags:
        - MobileAccessToken
      description: Revoke Access Token
      parameters:
          - name: case_id
            in: path
            required: true
            deprecated: false
            schema:
              type: varchar

      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'

components:
  securitySchemes:
    DeviceAPIAuth:
      description: This is for the Button Device Request
      type: http
      scheme: bearer
      bearerFormat: JWT 
    NormalAPIAuth:
      description: This is normal API
      type: http
      scheme: bearer
      
  schemas:
    Result:
      type: object
      properties:
        result: 
          description: Result of the Action
          type: string
          example: success
      



