openapi: 3.0.0
servers:
  - url: https://143.198.74.202
    description: Button Device Server
  ##- url: http://localhost
  ##  description: Button Device Server
info:
  title: Button Request
  version: 1.0.0
  description: >
    # Introduction
    
    Button Request is a platform for someone who want to replace tedious and repeated message with 
    a button. 
    
    ## API Categories

    There are only 1 category of API
   
    Below is the API classification
    
      - Button Device API

    ## API Operations

    ### Button Device API
    
    Using the Button Device API, you may send the defined messages to the console.

   

    # Authentication
  
    ##For Button Device API, the device id and the bearer token is the authentication method 



tags:
  - name: deviceAPI
    description: Button Device API
 
paths:
  
  '/deviceAPI/v1/{deviceId}':

    post:
      
      security:
        - DeviceAPIAuth: [] 
            
      tags:
        - deviceAPI
      description: Send a Button Request
      parameters:
          - name: deviceId
            in: path
            required: true
            deprecated: false
            schema:
              type: varchar
          - name: button_id
            in: query
            required: true
            deprecated: false
            schema:
              type: varchar
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
            
          
      
components:
  securitySchemes:
    DeviceAPIAuth:
      description: This is for the Button Device Request
      type: http
      scheme: bearer
      bearerFormat: JWT 

  schemas:
    Result:
      type: object
      properties:
        result: 
          description: Result of the Action
          type: string
          example: success
      



